name: story_maker_for_clip_studio
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.0.3
  scroll_to_index: any

  google_sign_in: ^5.3.0
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17

  file_picker: ^4.5.1

  flutter_launcher_icons: ^0.9.2
  auto_size_text: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: 源柔ゴシックＰ
      fonts:
        - asset: assets/fonts/GenJyuuGothic-P-Regular.ttf