// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2jHl8C8QXasCJ2lBhtmdZefmWiC1G5rI',
    appId: '1:372928743036:web:c4550bd18050af9121ebf9',
    messagingSenderId: '372928743036',
    projectId: 'storymaker-91db2',
    authDomain: 'storymaker-91db2.firebaseapp.com',
    storageBucket: 'storymaker-91db2.appspot.com',
    measurementId: 'G-6124LC93CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1gy5gYQaouE2-CXlu7xVX-XFOtxeTUH4',
    appId: '1:372928743036:android:6afc737385d6092621ebf9',
    messagingSenderId: '372928743036',
    projectId: 'storymaker-91db2',
    storageBucket: 'storymaker-91db2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8zE7IL-wdXco0fhHJE8s1x70JTwnHolc',
    appId: '1:372928743036:ios:f8f32741c7c7df0121ebf9',
    messagingSenderId: '372928743036',
    projectId: 'storymaker-91db2',
    storageBucket: 'storymaker-91db2.appspot.com',
    iosClientId: '372928743036-d8fegg4qn3h11jnjgugopgcoo25s94ja.apps.googleusercontent.com',
    iosBundleId: 'com.smsmsy.dev.storyMakerForClipStudio',
  );
}
